SELECT
	c.CLAIMID,
	CAST(c.DATEOFCLAIM AS DATE) AS claimDate,
	c.TOTALBILLED AS claimAmt,
	p.PATID,
	p.LASTNAME AS lastName,
	p.FIRSTNAME AS firstName,
	c.IDNUM AS subscribID,
	p.ID2 AS medicaid,
	CAST(p.BIRTHDATE AS DATE) AS Birthdate,
	CASE p.GENDER
		WHEN  1 THEN 'M'
		ELSE 'F'
	END AS sex,
	i.INSCONAME AS insurance,
	i.FINANCIALCLASS AS fClass,
	CAST(pr.PLDATE AS DATE) AS procDate,
	pr.AMOUNT AS lineAmt,
	ad.ADACODE AS code,
	r.RSCID AS clinic
FROM
	DDB_CLAIM AS c
	JOIN DDB_PAT AS p ON c.PATID = p.PATID
	JOIN DDB_INSURANCE AS i ON c.INSID = i.INSID
	JOIN DDB_PROC_LOG AS pr ON c.CLAIMID = pr.CLAIMID
	JOIN DDB_PROC_CODE AS ad ON pr.PROC_CODEID = ad.PROC_CODEID
	JOIN DDB_RSC AS r ON c.ClinicAppliedTo = r.URSCID
WHERE
	c.STATUS = 1
	AND c.TYPE = 2
	AND c.DATEOFCLAIM = '2014-02-06'
ORDER BY
	c.CLAIMID
